export { default as Header } from './Header';
export { default as Hero } from './Hero';
export { default as DropDown } from './DropDown';
export { default as About } from './About';
export { default as Project } from './Project';
export { default as Contact } from './Contact';
export { default as Services } from './Services';
export { default as Copyrights } from './Copyrights';
export { default as DropdownSwitch } from './DropdownSwitch';
